In [153]:
import numpy as np

In [273]:
A = np.array([[1, 2, 3], [2, 7, 4]])
B = np.array([[1, -1], [0,1]])
C = np.array([[5, -1], [9, 1], [6, 0]])
D = np.array([[3, -2, -1], [1, 2, 3]])
u = np.array([6, 2, -3, 5])
v = np.array([3, 5, -1, 4])
w = np.array([[1, 8, 0, 5]]).transpose()

In [272]:
print(A, '\n')
print(B, '\n')
print(C, '\n')
print(D, '\n')
print(u, '\n')
print(v, '\n')
print(w, '\n')

[[1 2 3]
 [2 7 4]] 

[[ 1 -1]
 [ 0  1]] 

[[ 5 -1]
 [ 9  1]
 [ 6  0]] 

[[ 3 -2 -1]
 [ 1  2  3]] 

[ 6  2 -3  5] 

[ 3  5 -1  4] 

[[1]
 [8]
 [0]
 [5]] 



In [161]:
dimension_dict = {
    "A": A.shape,
    "B": B.shape,
    "C": C.shape,
    "D": D.shape,
    "u": u.shape,
    "v": v.shape,
    "w": w.shape
}
dimension_dict

{'A': (2, 3),
 'B': (2, 2),
 'C': (3, 2),
 'D': (2, 3),
 'u': (4,),
 'v': (4,),
 'w': (4, 1)}

In [267]:
print(u + v)
print(np.add(u,v))

[ 9  7 -4  9]
[ 9  7 -4  9]


In [268]:
print(u - v)
print(np.subtract(u,v))

[ 3 -3 -2  1]
[ 3 -3 -2  1]


In [269]:
a = 6
print(a*u)
print(np.multiply(u,a))

[ 36  12 -18  30]
[ 36  12 -18  30]


In [172]:
# Dot product u.v
print(np.dot(u,v))

51


In [175]:
import math
sum_sq = 0
for coord in u:
    sum_sq += coord**2
print(math.sqrt(sum_sq))

print(np.linalg.norm(u))

8.602325267042627
8.602325267042627


In [204]:
# Question 12 Matrix Operation 1
try:
    print(np.add(A,C))
except ValueError:
    print('Cannot add matrices if the dimensions are not the same')


Cannot add matrices if the dimensions are not the same


In [205]:
# Question 13 Matrix Operation 2
try:
    print(np.subtract(A,C.transpose()))
except ValueError:
    print('Cannot subtract matrices if the dimensions are not the same')


[[-4 -7 -3]
 [ 3  6  4]]


In [206]:
# Question 14 Matrix Operation 3
try:
    print(np.add(C.transpose(),3*D))
except ValueError:
    print('Cannot add matrices if the dimensions are not the same')


[[14  3  3]
 [ 2  7  9]]


In [208]:
# Question 15 Matrix Operation 4
try:
    print(np.matmul(B,A))
except ValueError:
    print("Cannot multiple matrices if the inner-dimensions are not the same")

[[-1 -5 -1]
 [ 2  7  4]]


In [211]:
# Question 16 Matrix Operation 5
try:
    print(np.matmul(B,A.transpose()))
except ValueError:
    print("Cannot multiple matrices if the inner-dimensions are not the same")


Cannot multiple matrices if the inner-dimensions are not the same


In [257]:
# Question 17 Matrix Operation (Solution)
B = np.array([[1, -1], [0,1]])
np.linalg.matrix_power(B,4)


array([[ 1, -4],
       [ 0,  1]])

In [254]:
# Question 17 Matrix Operation (Solution 3)
# B^4
B = np.array([[1, -1], [0,1]])
b_1 = np.matmul(B,B) # multiplication 1 happens here already
b_2 = np.matmul(b_1, B) # multiplication 2 
b_3 = np.matmul(b_2, B) # multiplication 3
print(b_3)

[[ 1 -4]
 [ 0  1]]


In [255]:
# Question 17 Matrix Operation (Solution 3)

B = np.array([[1, -1], [0,1]])
power = 4
for n in range(1, power - 1):
    B = np.matmul(B,B)
print(B)

[[ 1 -4]
 [ 0  1]]


In [270]:
# Question 18: Coding (I just did above (-__-') )

# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u + v            # u+v
u_minus_v = u - v           # u-v
alpha_times_u = alpha * u       # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)             # u . v
norm_u =  np.linalg.norm(u)             # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C =  None           # A + C
A_minus_Ctranspose = np.subtract(A, C.transpose())   # A - C.T
Ctranspose_plus_3D = np.add(C.transpose(),(3*D))   # C.T + 3*D
B_times_A = np.matmul(B,A)            # B*A
B_times_Atranspose = None  # B*A.T

# Q4: (bonus)

B_times_C = None            # B*C
C_times_B = np.matmul(C,B)            # C*B
B_exp_4 =  np.linalg.matrix_power(B,4)             # B^4
A_times_Atranspose = np.matmul(A,A.transpose())   # A*A.T
Dtranspose_times_D = np.matmul(D.transpose(), D)   # D.T*D